# Generated by Django 3.2.7 on 2021-11-24 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Dispositivos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas_Frecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_problema', models.CharField(max_length=200)),
                ('descripcion_problema', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=datetime.date(2021, 11, 24))),
                ('fecha_entrega_estimada', models.DateField(blank=True, default=datetime.date(2021, 11, 24))),
                ('observaciones', models.TextField(blank=True, max_length=250)),
                ('codigo_desbloqueo', models.CharField(blank=True, max_length=10)),
                ('patron_desbloqueo', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_revision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_cierre_servicio', models.DateTimeField(blank=True, null=True)),
                ('solucion_final', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo')),
                ('estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.estado_orden')),
                ('problema_frecuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.problemas_frecuentes')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
            ],
        ),
    ]
