# Generated by Django 3.2.7 on 2021-09-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_entrega_estimada', models.DateField(blank=True)),
                ('observaciones', models.TextField(blank=True, max_length=250)),
                ('codigo_desbloqueo', models.CharField(blank=True, max_length=10)),
                ('patron_desbloqueo', models.IntegerField(blank=True)),
                ('valor_revision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_cierre_servicio', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.estado_orden')),
            ],
        ),
    ]
