# Generated by Django 3.2.7 on 2021-11-28 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 28)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 11, 28)),
        ),
    ]
