# Generated by Django 3.2.7 on 2021-09-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0002_alter_dispositivo_imei_opcional'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='dispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo'),
        ),
    ]
