# Generated by Django 3.2.7 on 2021-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_servicios_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemas_Frecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_problema', models.CharField(max_length=200)),
                ('descripcion_problema', models.TextField(blank=True)),
            ],
        ),
    ]
