# Generated by Django 3.2.7 on 2021-12-13 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_auto_20211128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 13)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 12, 13)),
        ),
    ]
