# Generated by Django 3.2.7 on 2021-12-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_auto_20211213_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 14)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 12, 14)),
        ),
    ]
