# Generated by Django 3.2.7 on 2021-10-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_problemas_frecuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='problema_frecuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.problemas_frecuentes'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='solucion_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
