# Generated by Django 3.2.7 on 2021-10-09 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_auto_20211009_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 9)),
        ),
    ]
