# Generated by Django 3.2.7 on 2021-10-09 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_alter_servicios_fecha_entrega_estimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_cierre_servicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 10, 9)),
        ),
    ]
