# Generated by Django 3.2.7 on 2021-11-03 20:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Servicios', '0006_auto_20211009_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 3)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 11, 3)),
        ),
    ]
