# Generated by Django 3.2.7 on 2021-11-11 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0001_initial'),
        ('Servicios', '0007_auto_20211103_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='tienda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 11)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2021, 11, 11)),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='patron_desbloqueo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
