# Generated by Django 3.2.7 on 2021-11-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0001_initial'),
        ('Trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tienda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda'),
            preserve_default=False,
        ),
    ]
