# Generated by Django 3.2.7 on 2021-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
