# Generated by Django 3.2.7 on 2021-11-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0003_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda_membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.membresia')),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
            ],
        ),
    ]
