# Generated by Django 3.2.7 on 2021-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0004_tienda_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda_membresia',
            name='fecha_activacion',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
