# Generated by Django 3.2.7 on 2021-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0005_tienda_membresia_fecha_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda_membresia',
            name='estado',
            field=models.CharField(choices=[('True', 'Activo'), ('False', 'Inactiva')], default=True, max_length=50),
        ),
    ]
