# Generated by Django 3.2.7 on 2021-12-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0006_tienda_membresia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda_membresia',
            name='estado',
            field=models.CharField(choices=[('True', 'Activo'), ('False', 'Inactiva'), ('Pendiente', 'Pendiente Pago')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda_membresia',
            name='membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tiendas.membresia'),
        ),
    ]
