# Generated by Django 3.2.7 on 2021-12-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0007_auto_20211213_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda_membresia',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.membresia'),
        ),
    ]
