# Generated by Django 3.2.7 on 2021-12-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0008_alter_tienda_membresia_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda_membresia',
            name='estado',
            field=models.CharField(choices=[('True', 'Activo'), ('False', 'Inactiva'), ('Pendiente Pago', 'Pendiente Pago')], default=True, max_length=50),
        ),
    ]
