# Generated by Django 3.2.7 on 2021-09-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.tipo_modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('imei_principal', models.BigIntegerField()),
                ('imei_opcional', models.BigIntegerField(blank=True)),
                ('direccion_mac', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('color_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.color_dispositivo')),
                ('modelo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.modelo_dispositivo')),
            ],
        ),
    ]
