# Generated by Django 3.2.7 on 2021-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imei_opcional',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
