# Generated by Django 3.2.7 on 2021-10-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0002_alter_dispositivo_imei_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='modelo_dispositivo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.marca_dispositivo'),
        ),
    ]
